# -*- coding: utf-8 -*-
{
    'name': 'Sơn Hà Kế toán',
    'version': '1.0',
    'summary': 'Module Kế Toán',
    'author': 'TrungNT2',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/acc_tai_khoan_views.xml',
        'views/acc_kho_views.xml',
        'views/acc_khoan_muc_views.xml',
        'views/acc_tinh_views.xml',
        'views/acc_tien_te_views.xml',
        'views/acc_nvbh_views.xml',
        'views/acc_loaidl_views.xml',
        'views/acc_bo_phan_views.xml',
        'views/acc_loai_hd_views.xml',
        'views/acc_vviec_views.xml',
        'views/acc_loai_nx_views.xml',
        'views/acc_tscd_views.xml',
        'views/acc_loai_kh_views.xml',
        'views/acc_chi_nhanh_views.xml',
        'views/acc_khach_hang_views.xml',
        'views/acc_loai_sp_views.xml',
        'views/acc_san_pham_views.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sonha_ke_toan/static/src/js/field_confirm_list_patch.js',
            'sonha_ke_toan/static/src/js/menu_item_patch.js',
            'sonha_ke_toan/static/src/css/style.css',
        ],
    },
    'installable': True,
    'application': False,
}
