# -*- coding: utf-8 -*-
{
    'name': 'Sơn Hà Kế toán',
    'version': '1.0',
    'summary': 'Module Kế Toán',
    'author': 'TrungNT2',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/acc_tai_khoan_views.xml',
        'views/acc_kho_views.xml',
        'views/acc_khoan_muc_views.xml',
        'views/acc_tinh_views.xml',
        'views/acc_tien_te_views.xml',
        'views/acc_nvbh_views.xml',
        'views/acc_loaidl_views.xml',
        'views/acc_bo_phan_views.xml',
        'views/acc_loai_hd_views.xml',
        'views/acc_vviec_views.xml',
        'views/acc_loai_nx_views.xml',
        'views/acc_tscd_views.xml',
        'views/acc_loai_kh_views.xml',
        'views/acc_chi_nhanh_views.xml',
        'views/acc_khach_hang_views.xml',
        'views/acc_loai_sp_views.xml',
        'views/acc_san_pham_views.xml',
        'views/acc_dong_hang_views.xml',
        'views/acc_loai_hh_views.xml',
        'views/acc_hang_hoa_views.xml',
        'views/acc_gia_mua_views.xml',
        'views/acc_gia_ban_views.xml',
        'views/acc_nguon_views.xml',
        'views/v_acc_san_pham_views.xml',
        'views/acc_bom_views.xml',
        'views/acc_thue_views.xml',
        'wizard/loai_dm_wizard_views.xml',
        'views/acc_ap_h_views.xml',
        'views/acc_ap_h_nk_views.xml',
        'views/acc_ap_h_ck_views.xml',
        'views/nl_acc_ap_tl_h_views.xml',
        'views/nl_acc_nk_sx_h_views.xml',
        'views/nl_acc_tong_hop_views.xml',
        'views/acc_tscd_gt_nc_h_views.xml',
        'views/acc_tscd_gt_lt_h_views.xml',
        'views/acc_tscd_gg_nc_h_views.xml',
        'views/acc_tscd_gg_lt_h_views.xml',
        'views/acc_kchuyen_views.xml',
        'wizard/thong_bao_wizard_views.xml',
        'wizard/popup_tim_kiem_views.xml',
        'wizard/popup_khau_hao_views.xml',
        'wizard/popup_gia_von_views.xml',
        'wizard/popup_kc_lai_lo_views.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sonha_ke_toan/static/src/js/auto_toggle_parent_fields.js',
            'sonha_ke_toan/static/src/js/field_confirm_list_patch.js',
            'sonha_ke_toan/static/src/js/menu_item_patch.js',
            'sonha_ke_toan/static/src/js/confirm_before_save.js',
            'sonha_ke_toan/static/src/css/style.css',
            'sonha_ke_toan/static/src/js/list_button.js',
            'sonha_ke_toan/static/src/xml/button_list_button.xml',
        ],
    },
    'installable': True,
    'application': False,
}
